function [C, L] = LAGRANGE (X,Y)
% X ES UN VECTOR QUE CONTIENE LAS LISTAS DE ABSISAS
% Y ES UN VECTOR QUE CONTIENE LAS LISTAS DE ORDENADAS
% C ES LA MATRIZ QUE CONTIENE LOS COEFICIENTES DEL POLINOMIO
% Li ES LA MATRIZ QUE CONTIENE LOS COEFICIENTES DDEL POLINOMIO DE LAGRANGE
w=length(X);
n=w-1;
L=zeros(w,w);
%FORMACION DE LOS POLINOMIO Li  LAGRANGE
for k=1:n+1
    V=1;
    for r=1:n+1;
        if k~=r
            V=conv(V,poly(X(r)))/(X(k)-X(r));
        end
    end
    L(k,:)=V;
end
% CALCULO DE LOS POLINOMIOS INTERPOLADOR 
C=Y*L;
