/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class PANT extends javax.swing.JFrame {

    /**
     * Creates new form PANT
     */
    public PANT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();
        encender = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        canal5 = new javax.swing.JButton();
        canal7 = new javax.swing.JButton();
        canal10 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        subirvol = new javax.swing.JLabel();
        bajarvol = new javax.swing.JLabel();
        volumen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 25));
        Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenMouseClicked(evt);
            }
        });

        encender.setText(" ENCENDER ");
        encender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 2, true));
        encender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encenderMouseClicked(evt);
            }
        });
        encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encenderActionPerformed(evt);
            }
        });

        apagar.setText("  APAGAR  ");
        apagar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        apagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagarMouseClicked(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jTextField1.setText(" CANALES DISPONIBLES ");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        canal5.setText("5");
        canal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canal5MouseClicked(evt);
            }
        });

        canal7.setText("7");
        canal7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canal7MouseClicked(evt);
            }
        });

        canal10.setText("10");
        canal10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canal10MouseClicked(evt);
            }
        });

        jTextField2.setText(" VOLUMEN ");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        subirvol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subirvol.setText(" + ");
        subirvol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subirvolMouseClicked(evt);
            }
        });

        bajarvol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bajarvol.setText(" - ");
        bajarvol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bajarvolMouseClicked(evt);
            }
        });

        volumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volumenMouseClicked(evt);
            }
        });

        jButton1.setText("6");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(encender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apagar)
                                .addGap(42, 42, 42)
                                .addComponent(canal5)
                                .addGap(37, 37, 37)
                                .addComponent(canal7)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addGap(12, 12, 12))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(canal10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(subirvol)
                                .addGap(65, 65, 65)
                                .addComponent(bajarvol))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(volumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encender)
                    .addComponent(apagar)
                    .addComponent(canal5)
                    .addComponent(canal7)
                    .addComponent(canal10)
                    .addComponent(subirvol, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajarvol)
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/inicio.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

        /*if (jComboBox1.getSelectedItem() == "inicio") {
            Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("inicio.jpg")));
        }   
        
        if (jComboBox1.getSelectedItem() == "encen1") {
            Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("encen1.gif")));
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagenMouseClicked

    private void encenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encenderMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/encender.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

        encender.setEnabled(false);
        apagar.setEnabled(true);
        /*if (jComboBox1.getSelectedItem() == "encender") {
            Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("encender.gif")));
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_encenderMouseClicked

    private void apagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagarMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/apagar.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

        encender.setEnabled(true);
        apagar.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_apagarMouseClicked

    private void canal5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canal5MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/can5.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_canal5MouseClicked

    private void canal10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canal10MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/can10.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_canal10MouseClicked

    private void canal7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canal7MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/can7.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_canal7MouseClicked

    private void volumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volumenMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/volumen.png");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(volumen.getWidth(), volumen.getHeight(), Image.SCALE_DEFAULT));
        volumen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_volumenMouseClicked

    private void subirvolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subirvolMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/subirvol.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(volumen.getWidth(), volumen.getHeight(), Image.SCALE_DEFAULT));
        volumen.setIcon(PM);

        // TODO add your handling code here:
    }//GEN-LAST:event_subirvolMouseClicked

    private void bajarvolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bajarvolMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/bajarvol.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(volumen.getWidth(), volumen.getHeight(), Image.SCALE_DEFAULT));
        volumen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_bajarvolMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/noticias.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton apagar;
    private javax.swing.JLabel bajarvol;
    private javax.swing.JButton canal10;
    private javax.swing.JButton canal5;
    private javax.swing.JButton canal7;
    private javax.swing.JButton encender;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel subirvol;
    private javax.swing.JLabel volumen;
    // End of variables declaration//GEN-END:variables
}
