/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class PC1 extends javax.swing.JPanel implements Runnable {

    int segundos = 0, minutos = 0, horas = 0;
    public static double totalf;
    double b;
    Thread h;

    @Override
    public void run() {

        while (true) {

            try {
                segundos++;
                cronometro1.setText(" " + horas + " : " + minutos + " : " + segundos);

                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(PC1.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (segundos == 59) {
                segundos = 0;
                minutos++;
            }

            if (minutos == 59) {
                minutos = 0;
                horas++;
            }

        }

    }

    /**
     * Creates new form PC1
     */
    public PC1() {
        initComponents();
        pausar1.setEnabled(false);
        continuar1.setEnabled(false);
        total1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iniciar1 = new javax.swing.JButton();
        pausar1 = new javax.swing.JButton();
        continuar1 = new javax.swing.JButton();
        cobrar1 = new javax.swing.JButton();
        total1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Registro1 = new javax.swing.JTextArea();
        cronometro1 = new javax.swing.JTextField();
        tf1 = new javax.swing.JTextField();

        jLabel1.setText("PC1");

        iniciar1.setText("Iniciar");
        iniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar1ActionPerformed(evt);
            }
        });

        pausar1.setText("Pausar");
        pausar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausar1ActionPerformed(evt);
            }
        });

        continuar1.setText("Continuar");
        continuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar1ActionPerformed(evt);
            }
        });

        cobrar1.setText("Cobrar");
        cobrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrar1ActionPerformed(evt);
            }
        });

        total1.setText("Total");
        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });

        Registro1.setColumns(20);
        Registro1.setRows(5);
        jScrollPane1.setViewportView(Registro1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(continuar1)
                            .addComponent(iniciar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cobrar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pausar1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total1)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cronometro1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cronometro1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar1)
                    .addComponent(pausar1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuar1)
                    .addComponent(cobrar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total1)
                .addGap(11, 11, 11)
                .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar1ActionPerformed

        h = new Thread(this);
        iniciar1.setEnabled(false);
        pausar1.setEnabled(true);
        total1.setEnabled(true);
        continuar1.setEnabled(true);
        h.start();

// TODO add your handling code here:
    }//GEN-LAST:event_iniciar1ActionPerformed

    private void pausar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausar1ActionPerformed

        continuar1.setEnabled(true);
        pausar1.setEnabled(false);

        h.suspend();

// TODO add your handling code here:
    }//GEN-LAST:event_pausar1ActionPerformed

    private void continuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar1ActionPerformed

        continuar1.setEnabled(false);
        pausar1.setEnabled(true);
        h.resume();
// TODO add your handling code here:
    }//GEN-LAST:event_continuar1ActionPerformed

    private void cobrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrar1ActionPerformed

        double total = 0;
        double total2 = 0;
        double total1 = 0;
        if (minutos >= 0 && minutos <= 30) {
            total = 5;

        } else if (minutos >= 31 && minutos <= 59) {
            total = 10;

        }

        total2 = horas * 10;
        total1 = total + total2;

        totalf = totalf + total1;

        Registro1.append("\n" + " El total es: " + total1);

        try {
            File f = new File("registro.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (f.exists()) {
                fw = new FileWriter(f, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("El Total de la Maquina 1 es: " + total1);

            } else {
                fw = new FileWriter(f);
                bw = new BufferedWriter(fw);
                bw.write("El Total de la Maquina 1 es: " + total1);
            }
            bw.close();
            fw.close();

        } catch (Exception ex) {
            Logger.getLogger(PC1.class.getName()).log(Level.SEVERE, null, ex);;

        }

        try {
            File f = new File("registro.txt");
            {
                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_cobrar1ActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed

        h.stop();

        segundos = 0;
        minutos = 0;
        horas = 0;
        cronometro1.setText("00:00:00");
        iniciar1.setEnabled(true);
        total1.setEnabled(false);
        pausar1.setEnabled(false);
        continuar1.setEnabled(false);
        cobrar1.setEnabled(true);

        tf1.setText("La cuenta total es: " + totalf + "\n");

        try {
            File v = new File("inventario.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (v.exists()) {
                fw = new FileWriter(v, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("" + "\n" + "La cuenta total de la maquina 1 es : " + totalf + "\n\n");

            } else {
                fw = new FileWriter(v);
                bw = new BufferedWriter(fw);
                bw.write("" + "\n" + "La cuenta total de la maquina 1 es: " + totalf + "\n\n");
            }
            bw.close();
            fw.close();

        } catch (Exception e) {
            System.out.println(e);

        }

        try {
            File v = new File("inventario.txt");
            {
                FileReader vr = new FileReader(v);
                BufferedReader br = new BufferedReader(vr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_total1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Registro1;
    private javax.swing.JButton cobrar1;
    private javax.swing.JButton continuar1;
    private javax.swing.JTextField cronometro1;
    private javax.swing.JButton iniciar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pausar1;
    private javax.swing.JTextField tf1;
    private javax.swing.JButton total1;
    // End of variables declaration//GEN-END:variables

    
}
