/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica;

import static Practica.PC1.totalf;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class PC2 extends javax.swing.JPanel implements Runnable{
    
    int segundos = 0, minutos = 0, horas = 0;
    public static double totalf2;
    double b;

    Thread h;

    @Override
    public void run() {

        while (true) {

            try {
                segundos++;
                cronometro2.setText(" " + horas + " : " + minutos + " : " + segundos);

                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(PC2.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (segundos == 59) {
                segundos = 0;
                minutos++;
            }

            if (minutos == 59) {
                minutos = 0;
                horas++;
            }

        }

    }

    /**
     * Creates new form PC2
     */
    public PC2() {
        initComponents();
        pausar2.setEnabled(false);
        continuar2.setEnabled(false);
        total2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PC2 = new javax.swing.JLabel();
        iniciar2 = new javax.swing.JButton();
        pausar2 = new javax.swing.JButton();
        continuar2 = new javax.swing.JButton();
        cobrar2 = new javax.swing.JButton();
        total2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Registro2 = new javax.swing.JTextArea();
        cronometro2 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();

        PC2.setText("PC2");

        iniciar2.setText("Iniciar");
        iniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar2ActionPerformed(evt);
            }
        });

        pausar2.setText("Pausar");
        pausar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausar2ActionPerformed(evt);
            }
        });

        continuar2.setText("Continuar");
        continuar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar2ActionPerformed(evt);
            }
        });

        cobrar2.setText("Cobrar");
        cobrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrar2ActionPerformed(evt);
            }
        });

        total2.setText("Total");
        total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total2ActionPerformed(evt);
            }
        });

        Registro2.setColumns(20);
        Registro2.setRows(5);
        jScrollPane1.setViewportView(Registro2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(total2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PC2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(continuar2)
                    .addComponent(iniciar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cobrar2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pausar2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf2)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cronometro2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(PC2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cronometro2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar2)
                    .addComponent(pausar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuar2)
                    .addComponent(cobrar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar2ActionPerformed

        h = new Thread(this);
        iniciar2.setEnabled(false);
        pausar2.setEnabled(true);
        total2.setEnabled(true);
        continuar2.setEnabled(true);
        h.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar2ActionPerformed

    private void pausar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausar2ActionPerformed

        continuar2.setEnabled(true);
        pausar2.setEnabled(false);

        h.suspend();

        // TODO add your handling code here:
    }//GEN-LAST:event_pausar2ActionPerformed

    private void continuar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar2ActionPerformed

        continuar2.setEnabled(false);
        pausar2.setEnabled(true);
        h.resume();
        // TODO add your handling code here:
    }//GEN-LAST:event_continuar2ActionPerformed

    private void cobrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrar2ActionPerformed

        double total = 0;
        double total2 = 0;
        double total1 = 0;
        if (minutos >= 0 && minutos <= 30) {
            total = 5;

        } else if (minutos >= 31 && minutos <= 59) {
            total = 10;

        }

        total2 = horas * 10;
        total1 = total + total2;

        totalf2 = totalf2 + total1;

        Registro2.append("\n" + " El total es: " + total1);

        try {
            File f = new File("registro.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (f.exists()) {
                fw = new FileWriter(f, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("El Total de la Maquina 2 es: " + total1);

            } else {
                fw = new FileWriter(f);
                bw = new BufferedWriter(fw);
                bw.write("El Total de la Maquina 2 es: " + total1);
            }
            bw.close();
            fw.close();

        } catch (Exception ex) {
            Logger.getLogger(PC1.class.getName()).log(Level.SEVERE, null, ex);;

        }

        try {
            File f = new File("registro.txt");
            {
                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cobrar2ActionPerformed

    private void total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total2ActionPerformed

        h.stop();

        segundos = 0;
        minutos = 0;
        horas = 0;
        cronometro2.setText("00:00:00");
        iniciar2.setEnabled(true);
        total2.setEnabled(false);
        pausar2.setEnabled(false);
        continuar2.setEnabled(false);
        cobrar2.setEnabled(true);

        tf2.setText("La cuenta total es: " + totalf2 + "\n");

        try {
            File v = new File("inventario.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (v.exists()) {
                fw = new FileWriter(v, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("" + "\n" + " La cuenta total de la maquina 2 es : " + totalf2 + "\n\n");

            } else {
                fw = new FileWriter(v);
                bw = new BufferedWriter(fw);
                bw.write("" + "\n" + "La cuenta total de la maquina 2 es: " + totalf2 + "\n\n");
            }
            bw.close();
            fw.close();

        } catch (Exception e) {
            System.out.println(e);

        }

        try {
            File v = new File("inventario.txt");
            {
                FileReader vr = new FileReader(v);
                BufferedReader br = new BufferedReader(vr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_total2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PC2;
    private javax.swing.JTextArea Registro2;
    private javax.swing.JButton cobrar2;
    private javax.swing.JButton continuar2;
    private javax.swing.JTextField cronometro2;
    private javax.swing.JButton iniciar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pausar2;
    private javax.swing.JTextField tf2;
    private javax.swing.JButton total2;
    // End of variables declaration//GEN-END:variables
}
