/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practica;

import static Practica.PC1.totalf;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class PC4 extends javax.swing.JPanel implements Runnable {

    int segundos = 0, minutos = 0, horas = 0;
    public static double totalf4;
    double b;

    Thread h;

    @Override
    public void run() {

        while (true) {

            try {
                segundos++;
                cronometro4.setText(" " + horas + " : " + minutos + " : " + segundos);

                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(PC4.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (segundos == 59) {
                segundos = 0;
                minutos++;
            }

            if (minutos == 59) {
                minutos = 0;
                horas++;
            }

        }

    }

    /**
     * Creates new form P0C4
     */
    public PC4() {
        initComponents();
        pausar4.setEnabled(false);
        continuar4.setEnabled(false);
        total4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iniciar4 = new javax.swing.JButton();
        pausar4 = new javax.swing.JButton();
        continuar4 = new javax.swing.JButton();
        cobrar4 = new javax.swing.JButton();
        total4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registro4 = new javax.swing.JTextArea();
        cronometro4 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();

        jLabel1.setText("PC4");

        iniciar4.setText("Iniciar");
        iniciar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciar4ActionPerformed(evt);
            }
        });

        pausar4.setText("Pausar");
        pausar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausar4ActionPerformed(evt);
            }
        });

        continuar4.setText("Continuar");
        continuar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuar4ActionPerformed(evt);
            }
        });

        cobrar4.setText("Cobrar");
        cobrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrar4ActionPerformed(evt);
            }
        });

        total4.setText("Total");
        total4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total4ActionPerformed(evt);
            }
        });

        registro4.setColumns(20);
        registro4.setRows(5);
        jScrollPane1.setViewportView(registro4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(continuar4)
                                    .addComponent(iniciar4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cobrar4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pausar4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(tf4))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total4)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cronometro4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(cronometro4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar4)
                    .addComponent(pausar4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuar4)
                    .addComponent(cobrar4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total4)
                .addGap(11, 11, 11)
                .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciar4ActionPerformed

        h = new Thread(this);
        iniciar4.setEnabled(false);
        pausar4.setEnabled(true);
        total4.setEnabled(true);
        continuar4.setEnabled(true);
        h.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_iniciar4ActionPerformed

    private void pausar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausar4ActionPerformed

        continuar4.setEnabled(true);
        pausar4.setEnabled(false);

        h.suspend();

        // TODO add your handling code here:
    }//GEN-LAST:event_pausar4ActionPerformed

    private void continuar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuar4ActionPerformed

        continuar4.setEnabled(false);
        pausar4.setEnabled(true);
        h.resume();
        // TODO add your handling code here:
    }//GEN-LAST:event_continuar4ActionPerformed

    private void cobrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrar4ActionPerformed

        double total = 0;
        double total2 = 0;
        double total1 = 0;
        if (minutos >= 0 && minutos <= 30) {
            total = 5;

        } else if (minutos >= 31 && minutos <= 59) {
            total = 10;

        }

        total2 = horas * 10;
        total1 = total + total2;

        totalf4 = totalf4 + total1;

        registro4.append("\n" + " El total es: " + total1);

        try {
            File f = new File("registro.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (f.exists()) {
                fw = new FileWriter(f, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("El Total de la Maquina 4 es: " + total1);

            } else {
                fw = new FileWriter(f);
                bw = new BufferedWriter(fw);
                bw.write("El Total de la Maquina 4 es: " + total1);
            }
            bw.close();
            fw.close();

        } catch (Exception ex) {
            Logger.getLogger(PC1.class.getName()).log(Level.SEVERE, null, ex);;

        }

        try {
            File f = new File("registro.txt");
            {
                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cobrar4ActionPerformed

    private void total4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total4ActionPerformed

        h.stop();

        segundos = 0;
        minutos = 0;
        horas = 0;
        cronometro4.setText("00:00:00");
        iniciar4.setEnabled(true);
        total4.setEnabled(false);
        pausar4.setEnabled(false);
        continuar4.setEnabled(false);
        cobrar4.setEnabled(true);

        tf4.setText("La cuenta total es: " + totalf4 + "\n");

        try {
            File v = new File("inventario.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (v.exists()) {
                fw = new FileWriter(v, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("" + "\n" + "La cuenta total de la maquina 4 es : " + totalf4 + "\n\n");

            } else {
                fw = new FileWriter(v);
                bw = new BufferedWriter(fw);
                bw.write("" + "\n" + "La cuenta total de la maquina 4 es: " + totalf4 + "\n\n");
            }
            bw.close();
            fw.close();

        } catch (Exception e) {
            System.out.println(e);

        }

        try {
            File v = new File("inventario.txt");
            {
                FileReader vr = new FileReader(v);
                BufferedReader br = new BufferedReader(vr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_total4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cobrar4;
    private javax.swing.JButton continuar4;
    private javax.swing.JTextField cronometro4;
    private javax.swing.JButton iniciar4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pausar4;
    private javax.swing.JTextArea registro4;
    private javax.swing.JTextField tf4;
    private javax.swing.JButton total4;
    // End of variables declaration//GEN-END:variables
}
