/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CCF;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class Panel extends javax.swing.JPanel implements Runnable {

    int segundos = 00;
    int minutos = 00;
    int horas = 00;
    Thread h;
    int nv = 1;

    @Override
    public void run() {

        while (true) {

            try {

                if (segundos < 60) {
                    cron.setText(horas + " : " + minutos + " : " + segundos);
                    Thread.sleep(100);
                    segundos++;
                } else {
                    segundos = 0;

                    if (minutos < 60) {
                        cron.setText(horas + " : " + minutos + " : " + segundos);

                        minutos++;

                    } else {
                        minutos = 0;
                        horas++;
                    }
                }

            } catch (InterruptedException ex) {
                Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        fin.setEnabled(false);
        text.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cron = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        inicio = new javax.swing.JButton();
        fin = new javax.swing.JButton();
        vuelt = new javax.swing.JButton();
        cobrar = new javax.swing.JButton();

        cron.setText("00:00:00");

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        inicio.setText("Iniciar");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        fin.setText("Terminar");
        fin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finActionPerformed(evt);
            }
        });

        vuelt.setText("Vuelta");
        vuelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueltActionPerformed(evt);
            }
        });

        cobrar.setText("Cobrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(cron, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vuelt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cobrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fin)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cron, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicio)
                    .addComponent(fin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vuelt)
                    .addComponent(cobrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void finActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finActionPerformed

        h.stop();
        segundos = 0;
        minutos = 0;
        horas = 0;
        inicio.setEnabled(true);

        fin.setEnabled(false);
        cron.setText("00 : 00 : 00");
        // TODO add your handling code here:
    }//GEN-LAST:event_finActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed

        h = new Thread(this);
        inicio.setEnabled(false);

        fin.setEnabled(true);
        text.setEnabled(true);
        h.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_inicioActionPerformed

    private void vueltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueltActionPerformed

        text.append("  Vuelta" + nv + " : " + horas + " : " + minutos + " : " + segundos + "\n");
        nv++;
        // TODO add your handling code here:
    }//GEN-LAST:event_vueltActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cobrar;
    private javax.swing.JLabel cron;
    private javax.swing.JButton fin;
    private javax.swing.JButton inicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    private javax.swing.JButton vuelt;
    // End of variables declaration//GEN-END:variables
}
