/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algorit;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.sun.xml.internal.fastinfoset.util.CharArray;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class C_Medios extends javax.swing.JFrame {

    /**
     * Creates new form C_Medios
     */
    public C_Medios() {
        initComponents();

        //Imagen de fondo
        this.setContentPane(fondo);
        //titulo
        setTitle("Michael Salgado Sotero");

        initComponents();

        //pantalla JFRAME centrada
        setLocationRelativeTo(null);
        //IMAGEN DE ICONO
        setIconImage(new ImageIcon(getClass().getResource("../algorit/ICONO.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsemilla = new javax.swing.JTextField();
        B_GENERAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_valores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_GENERAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_GENERAR.setText("GENERAR");
        B_GENERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GENERARActionPerformed(evt);
            }
        });

        tabla_valores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "n", "x0", "y0", "x1"
            }
        ));
        jScrollPane1.setViewportView(tabla_valores);

        jLabel1.setBackground(new java.awt.Color(255, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEMILLA :");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" .:: CUADRADOS MEDIOS  ::.");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtsemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B_GENERAR))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_GENERAR)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_GENERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GENERARActionPerformed
        // TODO add your handling code here:

        if (txtsemilla.getText().length() > 0 && Integer.parseInt(txtsemilla.getText()) > 999 && Integer.parseInt(txtsemilla.getText()) <= 10000) {
            ListaCM.init();

            boolean is_number = true;

            try {
                int a;
                a = Integer.parseInt(txtsemilla.getText().toString());
            } catch (java.lang.NumberFormatException nfe) {
                JOptionPane.showMessageDialog(rootPane, "No se puede procesar tu entrada, debes escribir caracteres numericos !");
                is_number = false;
            }

            if (is_number == true) {
                modelo = new DefaultTableModel();
                int contador = 0;
                int xaux = 0;
                String cadena = "";
                String[] columnas = {"n", "x0", "y0", "x1"};
                modelo.setColumnIdentifiers(columnas);
                modelo.setColumnIdentifiers(columnas);
                int seed = Integer.parseInt(txtsemilla.getText());
                xaux = seed;
                int copia = seed;
                while (true) {
                    int op = (seed * seed);
                    char[] numeros = ("" + op).toCharArray();

                    int longitud = numeros.length;
                    System.out.println("" + longitud);
                    if (longitud == 4) {
                        seed = op;
                    } else if (longitud == 1) {
                        cadena = "" + 0 + "" + 0 + "" + 0 + "" + numeros[0];
                        seed = Integer.parseInt(cadena);
                    } else if (longitud == 2) {
                        cadena = "" + 0 + "" + 0 + "" + numeros[0] + "" + numeros[1];
                        seed = Integer.parseInt(cadena);
                    } else if (longitud == 3) {
                        cadena = "" + 0 + "" + numeros[0] + "" + numeros[1] + "" + numeros[2];
                        seed = Integer.parseInt(cadena);
                    } else if (longitud == 5) {
                        cadena = "" + numeros[0] + "" + numeros[1] + "" + numeros[2] + "" + numeros[3];
                        seed = Integer.parseInt(cadena);
                    } else if (longitud == 6) {
                        cadena = "" + numeros[1] + "" + numeros[2] + "" + numeros[3] + "" + numeros[4];
                        seed = Integer.parseInt(cadena);
                    } else if (longitud == 7) {
                        cadena = "" + numeros[1] + "" + numeros[2] + "" + numeros[3] + "" + numeros[4];
                        seed = Integer.parseInt(cadena);
                    } else if (longitud == 8) {
                        cadena = "" + numeros[2] + "" + numeros[3] + "" + numeros[4] + "" + numeros[5];
                        seed = Integer.parseInt(cadena);
                    }
                    modelo.addRow(new Object[]{contador, xaux, op, cadena});
                    xaux = seed;
                    if (seed == copia) {
                        JOptionPane.showMessageDialog(rootPane, "La semilla inicial \"" + copia + "\" se repite en : " + contador);
                        break;
                    } else if (seed == 0) {
                        JOptionPane.showMessageDialog(rootPane, "El ciclo termina en 000 : " + contador);
                        break;
                    }
                    if (ListaCM.isEmpty()) {
                        ListaCM.add(cadena);
                    } else {
                        if (!ListaCM.ifExist(cadena)) {
                            ListaCM.add(cadena);
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "El numero se repite en " + contador);
                            break;
                        }
                    }

                    contador++;
                }
                tabla_valores.setModel(modelo);
            }
        } else if (txtsemilla.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "No debes dejar el campo de semilla vacio :(");
        } else if (Integer.parseInt(txtsemilla.getText()) <= 999 || Integer.parseInt(txtsemilla.getText()) >= 10000) {
            JOptionPane.showMessageDialog(rootPane, "El campo de la semilla debe ser de 4 digitos :v");
        }
    }//GEN-LAST:event_B_GENERARActionPerformed

    public static DefaultTableModel modelo;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Medios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Medios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_GENERAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_valores;
    private javax.swing.JTextField txtsemilla;
    // End of variables declaration//GEN-END:variables

    //AJUSTAR JFRAME Y FORMATO DE IMAGEN
    FondoPanel fondo = new FondoPanel();

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/algorit/cub.gif")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

}
