/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cronometros;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class ventana extends javax.swing.JPanel implements Runnable {
int segundos=00;
int minutos=00;
int horas=00; 

Thread hilo;

@Override
public void run(){
    while (true){
        
        try {
            
            
            if(segundos<60){
                               tiempo.setText(horas+" : "+minutos+" : "+segundos);
                               Thread.sleep(100);
                               segundos++;
                            }
            else {
                segundos=0;
                
            
            if(minutos<60){
                 tiempo.setText(horas+" : "+minutos+" : "+segundos);
                                
                                minutos++;
                                
                            }
            else {
                minutos=0;
                horas++;
            }}
            
        } catch (InterruptedException ex) {
            Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        pausa.setEnabled(false);
        continuar.setEnabled(false);
        terminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JButton();
        pausa = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        terminar = new javax.swing.JButton();
        tiempo = new javax.swing.JLabel();

        inicio.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        inicio.setText("INICIAR");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        pausa.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        pausa.setText("PAUSAR");
        pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaActionPerformed(evt);
            }
        });

        continuar.setFont(new java.awt.Font("HP Simplified", 0, 14)); // NOI18N
        continuar.setText("CONTINUAR");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });

        terminar.setFont(new java.awt.Font("HP Simplified", 0, 12)); // NOI18N
        terminar.setText("TERMINAR");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        tiempo.setFont(new java.awt.Font("HP Simplified", 0, 36)); // NOI18N
        tiempo.setText("00 : 00 : 00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pausa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continuar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inicio)
                    .addComponent(pausa)
                    .addComponent(continuar)
                    .addComponent(terminar))
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        hilo=new Thread(this);
        inicio.setEnabled(false);
        pausa.setEnabled(true);
        continuar.setEnabled(true);
        terminar.setEnabled(true);
        hilo.start();
    }//GEN-LAST:event_inicioActionPerformed

    private void pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaActionPerformed
        // TODO add your handling code here:
        hilo.suspend();
        pausa.setEnabled(false);
        continuar.setEnabled(true);
    }//GEN-LAST:event_pausaActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        // TODO add your handling code here:
        hilo.resume();
        continuar.setEnabled(false);
        pausa.setEnabled(true);
    }//GEN-LAST:event_continuarActionPerformed

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed
        // TODO add your handling code here:
        hilo.stop();
        segundos=0;
        minutos=0; horas=0;
        inicio.setEnabled(true);
        pausa.setEnabled(false);
        continuar.setEnabled(false);
        terminar.setEnabled(false);
        tiempo.setText("00 : 00 : 00");
    }//GEN-LAST:event_terminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuar;
    private javax.swing.JButton inicio;
    private javax.swing.JButton pausa;
    private javax.swing.JButton terminar;
    private javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
