/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2;

//import CIBER.control;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class k extends javax.swing.JPanel implements Runnable {

    int segundos = 0, minutos = 0, horas = 0;
    public static double totalf2;
    double b;

    Thread h;

    @Override
    public void run() {

        while (true) {

            try {
                segundos++;
                cronometro.setText(" " + horas + " : " + minutos + " : " + segundos);

                Thread.sleep(10);
            } catch (InterruptedException ex) {
                Logger.getLogger(k.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (segundos == 59) {
                segundos = 0;
                minutos++;
            }

            if (minutos == 59) {
                minutos = 0;
                horas++;
            }

        }

    }

    /**
     * Creates new form k
     */
    public k() {
        initComponents();
        p2.setEnabled(false);
        c2.setEnabled(false);
        t2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cronometro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        registro = new javax.swing.JTextArea();
        tf2 = new javax.swing.JTextField();
        i2 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        co2 = new javax.swing.JButton();
        t2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        cronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cronometroActionPerformed(evt);
            }
        });

        registro.setColumns(20);
        registro.setRows(5);
        jScrollPane1.setViewportView(registro);

        i2.setText("iniciar");
        i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2ActionPerformed(evt);
            }
        });

        p2.setText("pausar");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        c2.setText("continuar");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        co2.setText("cobrar");
        co2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co2ActionPerformed(evt);
            }
        });

        t2.setText("total");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        jLabel1.setText("maquina 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i2)
                            .addComponent(p2)
                            .addComponent(c2)
                            .addComponent(co2)
                            .addComponent(t2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(tf2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(i2)
                        .addGap(1, 1, 1)
                        .addComponent(p2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(co2)
                        .addGap(5, 5, 5)
                        .addComponent(t2)))
                .addGap(18, 18, 18)
                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cronometroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cronometroActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
        h.stop();

        segundos = 0;
        minutos = 0;
        horas = 0;
        cronometro.setText("00:00:00");
        i2.setEnabled(true);
        t2.setEnabled(false);
        p2.setEnabled(false);
        c2.setEnabled(false);
        co2.setEnabled(true);

        tf2.setText("cuenta total: " + totalf2 + "\n");

        try {
            File v = new File("inventario.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (v.exists()) {
                fw = new FileWriter(v, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("--" + "\n" + "cuenta total de la maquina 2 es: " + totalf2 + "\n\n");

            } else {
                fw = new FileWriter(v);
                bw = new BufferedWriter(fw);
                bw.write("----" + "\n" + "cuenta total de la maquina 2 es: " + totalf2 + "\n\n");
            }
            bw.close();
            fw.close();

        } catch (Exception e) {
            System.out.println(e);

        }

        try {
            File v = new File("inventario.txt");
            {
                FileReader vr = new FileReader(v);
                BufferedReader br = new BufferedReader(vr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_t2ActionPerformed

    private void co2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co2ActionPerformed
        // TODO add your handling code here:
        double total = 0;
        double total2 = 0;
        double total1 = 0;
        if (minutos >= 0 && minutos <= 30) {
            total = 5;

        } else if (minutos >= 31 && minutos <= 59) {
            total = 10;

        }

        total2 = horas * 10;
        total1 = total + total2;
        totalf2 = totalf2 + total1;
        registro.append("\n" + " total es: " + total1);

        try {
            File f = new File("registro.txt");

            FileWriter fw;
            BufferedWriter bw;
            if (f.exists()) {
                fw = new FileWriter(f, true);
                bw = new BufferedWriter(fw);
                bw.newLine();
                bw.write("maquina 2 el total es: " + total1);

            } else {
                fw = new FileWriter(f);
                bw = new BufferedWriter(fw);
                bw.write("maquina 2 " + "el total es: " + total1);
            }
            bw.close();
            fw.close();

        } catch (Exception ex) {
            Logger.getLogger(control.class.getName()).log(Level.SEVERE, null, ex);;

        }

        try {
            File f = new File("registro.txt");
            {
                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                String linea;

            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_co2ActionPerformed

    private void i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2ActionPerformed
        // TODO add your handling code here:
        h = new Thread(this);
        i2.setEnabled(false);
        p2.setEnabled(true);
        t2.setEnabled(true);
        c2.setEnabled(true);
        h.start();
    }//GEN-LAST:event_i2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
        c2.setEnabled(true);
        p2.setEnabled(false);

        h.suspend();
    }//GEN-LAST:event_p2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
        c2.setEnabled(false);
        p2.setEnabled(true);
        h.resume();
    }//GEN-LAST:event_c2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c2;
    private javax.swing.JButton co2;
    private javax.swing.JTextField cronometro;
    private javax.swing.JButton i2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton p2;
    private javax.swing.JTextArea registro;
    private javax.swing.JButton t2;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
