/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class maq4 extends javax.swing.JPanel implements Runnable {
    int segundos=0, minutos = 0, horas = 0;
    public static double totalf4;
   double b;
     
    Thread h;
    @Override
    
    public void run(){
         
        
     while(true){
        
         try {
             segundos++;
             cronometro.setText(" "+horas+" : "+minutos+" : "+ segundos);
             
             Thread.sleep(10);
         } catch (InterruptedException ex) {
             Logger.getLogger(maq4.class.getName()).log(Level.SEVERE, null, ex);
         }
     if(segundos == 59 ){
     segundos = 0;
     minutos++;
     }
     
     if (minutos == 59){
         minutos = 0;
     horas++;
     }
     
     }
    }

    /**
     * Creates new form maq4
     */
    public maq4() {
        initComponents();
         p4.setEnabled(false);
         c4.setEnabled(false);
         t4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cronometro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        registro = new javax.swing.JTextArea();
        tf4 = new javax.swing.JTextField();
        i4 = new javax.swing.JButton();
        p4 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        co4 = new javax.swing.JButton();
        t4 = new javax.swing.JButton();

        jLabel1.setText("maquina 4");

        registro.setColumns(20);
        registro.setRows(5);
        jScrollPane1.setViewportView(registro);

        i4.setText("iniciar");
        i4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i4ActionPerformed(evt);
            }
        });

        p4.setText("pausar");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        c4.setText("continuar");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        co4.setText("cobrar");
        co4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co4ActionPerformed(evt);
            }
        });

        t4.setText("total");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(i4)
                            .addComponent(p4)
                            .addComponent(c4)
                            .addComponent(co4)
                            .addComponent(t4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf4, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(i4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(co4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t4)))
                .addGap(0, 33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void i4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i4ActionPerformed
        // TODO add your handling code here:
        h=new Thread(this);
        i4.setEnabled(false);
        p4.setEnabled(true);
        t4.setEnabled(true);
        c4.setEnabled(true);
          h.start();
    }//GEN-LAST:event_i4ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
        c4.setEnabled(true);
        p4.setEnabled(false);

       h.suspend();
        
    }//GEN-LAST:event_p4ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
        c4.setEnabled(false);
        p4.setEnabled(true);
                       h.resume();
    }//GEN-LAST:event_c4ActionPerformed

    private void co4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co4ActionPerformed
        // TODO add your handling code here:
        double total=0;
         double total2=0;
         double total1=0;
        if(minutos>=0 && minutos <=30){
             total =  5;
             
        }
        else if(minutos>=31 && minutos <=59){
             total =  10;
        
        }
        
             total2 =horas  * 10;
      total1 = total+ total2;
       totalf4= totalf4 + total1;
       
        registro.append("\n" +  " total es: "+total1  ); 
        
        
       
        
          try{ 
            File f= new File("registro.txt");
           
            FileWriter fw;
            BufferedWriter bw;
            if(f.exists()){
                fw=new FileWriter(f, true);
                bw=new  BufferedWriter(fw);
                bw.newLine();
                bw.write("maquina 4 " +  "el total es: "+total1 );
                
            } else{
                fw=new FileWriter(f);
                bw=new BufferedWriter(fw);
                 bw.write("maquina 4 "+  "el total es: "+total1 );
            }
            bw.close();
            fw.close();
         
            
        }catch (Exception ex){
            Logger.getLogger(maq4.class.getName()).log(Level.SEVERE, null, ex);;
                
            
        }
    
         try {
                File f=new File("registro.txt");
                {
                FileReader fr=new FileReader(f);
                BufferedReader br=new BufferedReader(fr);
                String linea;
                
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_co4ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
        h.stop();
        
        segundos=0;
       minutos=0;
        horas=0;
       cronometro.setText("00:00:00");
        i4.setEnabled(true);
        t4.setEnabled(false);
        p4.setEnabled(false);
        c4.setEnabled(false);
        co4.setEnabled(true);
        
               tf4.setText("cuenta total: "+totalf4 + "\n" );
     
         try{ 
            File v= new File("inventario.txt");
           
            FileWriter fw;
            BufferedWriter bw;
            if(v.exists()){
                fw=new FileWriter(v, true);
                bw=new  BufferedWriter(fw);
                bw.newLine();
                bw.write("--" +"\n" + "cuenta total de la maquina 4 es: "+totalf4 + "\n\n" );
              
            } else{
                fw=new FileWriter(v);
                bw=new BufferedWriter(fw);
                 bw.write("--------------------------" +"\n" + "cuenta total: "+totalf4 +  "\n\n" );
            }
            bw.close();
            fw.close();
         
            
        }catch (Exception e){
                System.out.println(e);
            
        }
    
        try {
                File v=new File("inventario.txt");
                {
                FileReader vr=new FileReader(v);
                BufferedReader br=new BufferedReader(vr);
                String linea;
                
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_t4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c4;
    private javax.swing.JButton co4;
    private javax.swing.JTextField cronometro;
    private javax.swing.JButton i4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton p4;
    private javax.swing.JTextArea registro;
    private javax.swing.JButton t4;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
