/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class maq5 extends javax.swing.JPanel implements Runnable {
     int segundos=0, minutos = 0, horas = 0;
   public static  double totalf5;
   double b;
     
    Thread h;
    @Override
    
    public void run(){
         
        
     while(true){
        
         try {
             segundos++;
             cronometro.setText(" "+horas+" : "+minutos+" : "+ segundos);
             
             Thread.sleep(10);
         } catch (InterruptedException ex) {
             Logger.getLogger(maq5.class.getName()).log(Level.SEVERE, null, ex);
         }
     if(segundos == 59 ){
     segundos = 0;
     minutos++;
     }
     
     if (minutos == 59){
         minutos = 0;
     horas++;
     }
     
     }
    }
    

    /**
     * Creates new form maq5
     */
    public maq5() {
        initComponents();
         p5.setEnabled(false);
         c5.setEnabled(false);
         t5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cronometro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        registro = new javax.swing.JTextArea();
        tf5 = new javax.swing.JTextField();
        i5 = new javax.swing.JButton();
        p5 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        co5 = new javax.swing.JButton();
        t5 = new javax.swing.JButton();

        jLabel1.setText("maquina 5");

        registro.setColumns(20);
        registro.setRows(5);
        jScrollPane1.setViewportView(registro);

        i5.setText("iniciar");
        i5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i5ActionPerformed(evt);
            }
        });

        p5.setText("pausar");
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        c5.setText("continuar");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        co5.setText("cobrar");
        co5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co5ActionPerformed(evt);
            }
        });

        t5.setText("terminar");
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(i5)
                        .addComponent(p5)
                        .addComponent(c5)
                        .addComponent(co5)
                        .addComponent(t5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf5, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(i5)
                        .addGap(3, 3, 3)
                        .addComponent(p5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(co5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t5)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void i5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i5ActionPerformed
        // TODO add your handling code here:
         h=new Thread(this);
        i5.setEnabled(false);
        p5.setEnabled(true);
        t5.setEnabled(true);
        c5.setEnabled(true);
          h.start();
    }//GEN-LAST:event_i5ActionPerformed

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        // TODO add your handling code here:
        c5.setEnabled(true);
        p5.setEnabled(false);

       h.suspend();
    }//GEN-LAST:event_p5ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        c5.setEnabled(false);
        p5.setEnabled(true);
                       h.resume();
    }//GEN-LAST:event_c5ActionPerformed

    private void co5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co5ActionPerformed
        // TODO add your handling code here:
          double total=0;
         double total2=0;
         double total1=0;
        if(minutos>=0 && minutos <=30){
             total =  5;
             
        }
        else if(minutos>=31 && minutos <=59){
             total =  10;
        
        }
        
             total2 =horas  * 10;
      total1 = total+ total2;
       totalf5= totalf5 + total1;
       
        registro.append("\n" +  " total es: "+total1  );  
          try{ 
            File f= new File("registro.txt");
           
            FileWriter fw;
            BufferedWriter bw;
            if(f.exists()){
                fw=new FileWriter(f, true);
                bw=new  BufferedWriter(fw);
                bw.newLine();
                bw.write("maquina 5 " +  "el total es: "+total1 );
                
            } else{
                fw=new FileWriter(f);
                bw=new BufferedWriter(fw);
                 bw.write("maquina 5 "+  "el total es: "+total1 );
            }
            bw.close();
            fw.close();
         
            
        }catch (Exception ex){
            Logger.getLogger(maq5.class.getName()).log(Level.SEVERE, null, ex);;
                
            
        }
    
         try {
                File f=new File("registro.txt");
                {
                FileReader fr=new FileReader(f);
                BufferedReader br=new BufferedReader(fr);
                String linea;
                
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_co5ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
        h.stop();
        
        segundos=0;
       minutos=0;
        horas=0;
       cronometro.setText("00:00:00");
        i5.setEnabled(true);
        t5.setEnabled(false);
        p5.setEnabled(false);
        c5.setEnabled(false);
        co5.setEnabled(true);
        
               tf5.setText("cuenta total: "+totalf5 + "\n" );
     
         try{ 
            File v= new File("inventario.txt");
           
            FileWriter fw;
            BufferedWriter bw;
            if(v.exists()){
                fw=new FileWriter(v, true);
                bw=new  BufferedWriter(fw);
                bw.newLine();
                bw.write("--" +"\n" + "cuenta total de la maquina 5 es: "+totalf5 + "\n\n" );
              
            } else{
                fw=new FileWriter(v);
                bw=new BufferedWriter(fw);
                 bw.write("--------------------------" +"\n" + "cuenta total: "+totalf5 +  "\n\n" );
            }
            bw.close();
            fw.close();
         
            
        }catch (Exception e){
                System.out.println(e);
            
        }
    
        try {
                File v=new File("inventario.txt");
                {
                FileReader vr=new FileReader(v);
                BufferedReader br=new BufferedReader(vr);
                String linea;
                
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_t5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c5;
    private javax.swing.JButton co5;
    private javax.swing.JTextField cronometro;
    private javax.swing.JButton i5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton p5;
    private javax.swing.JTextArea registro;
    private javax.swing.JButton t5;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
