/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class maq6 extends javax.swing.JPanel implements Runnable {
    int segundos=0, minutos = 0, horas = 0;
     public static double totalf6;
   double b;
     
    Thread h;
    @Override
    
    public void run(){
         
        
     while(true){
        
         try {
             segundos++;
             cronometro.setText(" "+horas+" : "+minutos+" : "+ segundos);
             
             Thread.sleep(10);
         } catch (InterruptedException ex) {
             Logger.getLogger(maq6.class.getName()).log(Level.SEVERE, null, ex);
         }
     if(segundos == 59 ){
     segundos = 0;
     minutos++;
     }
     
     if (minutos == 59){
         minutos = 0;
     horas++;
     }
     
     }
    }
    

    /**
     * Creates new form maq6
     */
    public maq6() {
        initComponents();
         p6.setEnabled(false);
         c6.setEnabled(false);
         t6.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cronometro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        registro = new javax.swing.JTextArea();
        tf6 = new javax.swing.JTextField();
        i6 = new javax.swing.JButton();
        p6 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        co6 = new javax.swing.JButton();
        t6 = new javax.swing.JButton();

        jLabel1.setText("maquina 6");

        registro.setColumns(20);
        registro.setRows(5);
        jScrollPane1.setViewportView(registro);

        i6.setText("iniciar");
        i6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i6ActionPerformed(evt);
            }
        });

        p6.setText("pausar");
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });

        c6.setText("continuar");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        co6.setText("cobrar");
        co6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co6ActionPerformed(evt);
            }
        });

        t6.setText("total");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(i6)
                    .addComponent(p6)
                    .addComponent(c6)
                    .addComponent(co6)
                    .addComponent(t6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf6, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(tf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cronometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(i6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(co6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void i6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i6ActionPerformed
        // TODO add your handling code here:
         h=new Thread(this);
        i6.setEnabled(false);
        p6.setEnabled(true);
        t6.setEnabled(true);
        c6.setEnabled(true);
          h.start();
    }//GEN-LAST:event_i6ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        // TODO add your handling code here:
        c6.setEnabled(true);
        p6.setEnabled(false);

       h.suspend();
    }//GEN-LAST:event_p6ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
        c6.setEnabled(false);
        p6.setEnabled(true);
                       h.resume();
    }//GEN-LAST:event_c6ActionPerformed

    private void co6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co6ActionPerformed
        // TODO add your handling code here:
        double total=0;
         double total2=0;
         double total1=0;
        if(minutos>=0 && minutos <=30){
             total =  5;
             
        }
        else if(minutos>=31 && minutos <=59){
             total =  10;
        
        }
        
             total2 =horas  * 10;
      total1 = total+ total2;
       totalf6= totalf6 + total1;
       
        registro.append("\n" +  " total es: "+total1  ); 
        
        
       
        
          try{ 
            File f= new File("registro.txt");
           
            FileWriter fw;
            BufferedWriter bw;
            if(f.exists()){
                fw=new FileWriter(f, true);
                bw=new  BufferedWriter(fw);
                bw.newLine();
                bw.write("maquina 6" +  "el total es: "+ total1 );
                
            } else{
                fw=new FileWriter(f);
                bw=new BufferedWriter(fw);
                 bw.write("maquina 6 "+  "el total es: "+ total1 );
            }
            bw.close();
            fw.close();
         
            
        }catch (Exception ex){
            Logger.getLogger(maq6.class.getName()).log(Level.SEVERE, null, ex);;
                
            
        }
    
         try {
                File f=new File("registro.txt");
                {
                FileReader fr=new FileReader(f);
                BufferedReader br=new BufferedReader(fr);
                String linea;
                
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_co6ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
        h.stop();
        
        segundos=0;
       minutos=0;
        horas=0;
       cronometro.setText("00:00:00");
        i6.setEnabled(true);
        t6.setEnabled(false);
        p6.setEnabled(false);
        c6.setEnabled(false);
        co6.setEnabled(true);
        
               tf6.setText("cuenta total: "+ totalf6 + "\n" );
     
         try{ 
            File v= new File("inventario.txt");
           
            FileWriter fw;
            BufferedWriter bw;
            if(v.exists()){
                fw=new FileWriter(v, true);
                bw=new  BufferedWriter(fw);
                bw.newLine();
                bw.write("--" +"\n" + "cuenta total de la maquina 6 es: "+ totalf6 + "\n\n" );
              
            } else{
                fw=new FileWriter(v);
                bw=new BufferedWriter(fw);
                 bw.write("--------------------------" +"\n" + "cuenta total: "+totalf6 +  "\n\n" );
            }
            bw.close();
            fw.close();
         
            
        }catch (Exception e){
                System.out.println(e);
            
        }
    
        try {
                File v=new File("inventario.txt");
                {
                FileReader vr=new FileReader(v);
                BufferedReader br=new BufferedReader(vr);
                String linea;
                
                }
                
            } catch (Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_t6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c6;
    private javax.swing.JButton co6;
    private javax.swing.JTextField cronometro;
    private javax.swing.JButton i6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton p6;
    private javax.swing.JTextArea registro;
    private javax.swing.JButton t6;
    private javax.swing.JTextField tf6;
    // End of variables declaration//GEN-END:variables
}
