/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mm;

import MetodosSql.ConexionBD;
import MetodosSql.Metodos_SQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Frm_interfaz extends javax.swing.JFrame {

    Metodos_SQL metodos = new Metodos_SQL();
    ConexionBD cc = new ConexionBD();
    Connection cn = cc.conectar();

    DefaultTableModel modelo;

    void mostrardatosusuario(String valor) {
        DefaultTableModel ussuario = new DefaultTableModel();
        ussuario.addColumn("\t\tNombre");
        ussuario.addColumn("\tApellido");
        ussuario.addColumn("\t\tCorreo");
        ussuario.addColumn("\t\tContraseña");
        tbusuarios.setModel(ussuario);
        String sql = "";

        if (valor.equals("")) {
            sql = "SELECT *FROM usuarios";

        } else {
            sql = "SELECT *FROM usuarios WHERE nombre='" + valor + "'";

        }

        String[] datos = new String[4];

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                ussuario.addRow(datos);

            }
            tbusuarios.setModel(ussuario);

        } catch (SQLException ex) {
            Logger.getLogger(Frm_interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public Frm_interfaz() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("nombre");
        modelo.addColumn("apellido");
        modelo.addColumn("correo");
        modelo.addColumn("contraseña");
        /////////tablas
        mostrardatosusuario("");
        /*mostrarpedidos("");
        mostrarclientes("");*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        codcorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codapellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        codnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusuarios = new javax.swing.JTable();
        bususuario = new javax.swing.JTextField();
        buscarusuario = new javax.swing.JButton();
        musuario = new javax.swing.JButton();
        gusuario = new javax.swing.JButton();
        ausuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codcontra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        borrarusuario = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("INTERFAZ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        codcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codcorreoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Apellido");

        codapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codapellidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre");

        codnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codnombreActionPerformed(evt);
            }
        });

        tbusuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbusuarios);

        bususuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bususuarioActionPerformed(evt);
            }
        });

        buscarusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscarusuario.setText("Buscar");
        buscarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarusuarioActionPerformed(evt);
            }
        });

        musuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        musuario.setText("Mostrar Datos");
        musuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musuarioActionPerformed(evt);
            }
        });

        gusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gusuario.setText("Guardar");
        gusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gusuarioActionPerformed(evt);
            }
        });

        ausuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ausuario.setText("Actualizar");
        ausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausuarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("USUARIOS");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        codcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codcontraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Contraseña");

        borrarusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        borrarusuario.setText("Borrar");
        borrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarusuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buscarusuario)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gusuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(borrarusuario)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bususuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(ausuario)
                                .addGap(18, 18, 18)
                                .addComponent(musuario)))))
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(314, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarusuario)
                    .addComponent(bususuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gusuario)
                    .addComponent(ausuario)
                    .addComponent(musuario)
                    .addComponent(borrarusuario))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(330, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codcorreoActionPerformed

    private void codapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codapellidoActionPerformed

    private void codnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codnombreActionPerformed

    private void bususuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bususuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bususuarioActionPerformed

    private void buscarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarusuarioActionPerformed
        // TODO add your handling code here:
        mostrardatosusuario(bususuario.getText());
    }//GEN-LAST:event_buscarusuarioActionPerformed

    private void musuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musuarioActionPerformed
        // TODO add your handling code here:
        mostrardatosusuario("");
    }//GEN-LAST:event_musuarioActionPerformed

    private void gusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gusuarioActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement psusuario = cn.prepareStatement("INSERT INTO usuarios(nombre,apellido,correo,contraseña) VALUES (?,?,?,?)");
            psusuario.setString(1, codnombre.getText());
            psusuario.setString(2, codapellido.getText());
            psusuario.setString(3, codcorreo.getText());
            psusuario.setString(4, codcontra.getText());

            psusuario.executeUpdate();
            mostrardatosusuario("");
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_gusuarioActionPerformed

    private void ausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausuarioActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement psusuario = cn.prepareStatement("UPDATE usuarios SET apellido='" + codapellido.getText() + "',correo='" + codcorreo.getText() + "',contraseña='" + codcontra.getText() + "' WHERE nombre='" + codnombre.getText() + "'");
            psusuario.executeUpdate();
            mostrardatosusuario("");
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_ausuarioActionPerformed

    private void codcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codcontraActionPerformed

    private void borrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarusuarioActionPerformed

        int fila = tbusuarios.getSelectedRow();
        if (fila > 0) {
            modelo.removeRow(fila);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccionar Fila");
        }


    }//GEN-LAST:event_borrarusuarioActionPerformed

    private void tbusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbusuariosMouseClicked

        int fila = tbusuarios.getSelectedRow();

        String nom = "";

        nom = tbusuarios.getValueAt(fila, 0).toString();

        try {
            PreparedStatement psproductos = cn.prepareStatement("DELETE FROM usuarios WHERE  nombre='" + nom + "'");
            psproductos.executeUpdate();
            mostrardatosusuario("");
        } catch (Exception e) {
        }
        /*//////////////
            int fila2 = tbusuarios.getSelectedRow();
   

    if (fila2 >= 0) {
        codnombre.setText(tbusuarios.getValueAt(fila2, 0).toString());
        codapellido.setText(tbusuarios.getValueAt(fila2, 1).toString());
        codcorreo.setText(tbusuarios.getValueAt(fila2, 2).toString());
        codcontra.setText(tbusuarios.getValueAt(fila2, 3).toString());
    } else {
        JOptionPane.showMessageDialog(null, "no seleciono fila");
    }*/


    }//GEN-LAST:event_tbusuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ausuario;
    private javax.swing.JButton borrarusuario;
    private javax.swing.JButton buscarusuario;
    private javax.swing.JTextField bususuario;
    private javax.swing.JTextField codapellido;
    private javax.swing.JTextField codcontra;
    private javax.swing.JTextField codcorreo;
    private javax.swing.JTextField codnombre;
    private javax.swing.JButton gusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton musuario;
    private javax.swing.JTable tbusuarios;
    // End of variables declaration//GEN-END:variables
}
