/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRACT3;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class Cronos extends javax.swing.JPanel implements Runnable {

    int segundos = 00;
    int minutos = 00;
    int horas = 00;
    Thread h;
    int nv = 1;

    @Override
    public void run() {

        while (true) {

            try {

                if (segundos < 60) {
                    crono.setText(horas + " : " + minutos + " : " + segundos);
                    Thread.sleep(100);
                    segundos++;
                } else {
                    segundos = 0;

                    if (minutos < 60) {
                        crono.setText(horas + " : " + minutos + " : " + segundos);

                        minutos++;

                    } else {
                        minutos = 0;
                        horas++;
                    }
                }

            } catch (InterruptedException ex) {
                Logger.getLogger(Cronos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    /**
     * Creates new form NewJPanel
     */
    public Cronos() {
        initComponents();
        pausar.setEnabled(false);
        continuar.setEnabled(false);
        terminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        iniciar = new javax.swing.JButton();
        pausar = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        terminar = new javax.swing.JButton();
        crono = new javax.swing.JLabel();
        vueltas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        vuelta = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        pausar.setText("Pausar");
        pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarActionPerformed(evt);
            }
        });

        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });

        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        crono.setFont(new java.awt.Font("HP Simplified", 0, 36)); // NOI18N
        crono.setForeground(new java.awt.Color(0, 0, 204));
        crono.setText("00 : 00 : 00");

        vueltas.setText("Vueltas");
        vueltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vueltasActionPerformed(evt);
            }
        });

        vuelta.setColumns(20);
        vuelta.setRows(5);
        jScrollPane3.setViewportView(vuelta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(continuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(terminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pausar)))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(crono, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(vueltas))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(crono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar)
                    .addComponent(pausar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuar)
                    .addComponent(terminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vueltas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed

        h.stop();
        segundos = 0;
        minutos = 0;
        horas = 0;
        iniciar.setEnabled(true);
        pausar.setEnabled(false);
        continuar.setEnabled(false);
        terminar.setEnabled(false);
        crono.setText("00 : 00 : 00");

        // TODO add your handling code here:
    }//GEN-LAST:event_terminarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed

        h = new Thread(this);
        iniciar.setEnabled(false);
        pausar.setEnabled(true);
        continuar.setEnabled(true);
        terminar.setEnabled(true);
        h.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarActionPerformed

    private void pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarActionPerformed

        h.suspend();
        pausar.setEnabled(false);
        continuar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_pausarActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed

        h.resume();
        continuar.setEnabled(false);
        pausar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_continuarActionPerformed

    private void vueltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vueltasActionPerformed

        vuelta.append("Vuelta" + nv + " : " + horas + " : " + minutos + " : " + segundos + "\n");
        nv++;
        // TODO add your handling code here:
    }//GEN-LAST:event_vueltasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuar;
    private javax.swing.JLabel crono;
    private javax.swing.JButton iniciar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pausar;
    private javax.swing.JButton terminar;
    private javax.swing.JTextArea vuelta;
    private javax.swing.JButton vueltas;
    // End of variables declaration//GEN-END:variables
}
