/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caballos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author Acer
 */
public class panel extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form lienzo
     */
    Thread hilo;
    int x = getWidth() / 2;
    int y = getWidth() / 2;
    //int y = getHeight() / 2;
    //Image cab;

    public panel() {
        initComponents();
        hilo = new Thread(this);
    }

    /*
  public void init() {
    this.setSize(400,300);
    cab=getImage("caballo1.png");
    cab=getImage("caballo2.png");
  }
     */
    @Override
    public void paint(Graphics g) {
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getWidth());
        g.setColor(Color.blue);
        g.setColor(Color.blue);
        g.fillRect(x, getHeight() / 2, 30, 30);
        g.fillRect(y, getWidth() / 2, 30, 30);

        //g.drawImage(cab, 250, 50, this);
    }

    public void inicio() {
        hilo.start();
    }

    public void pausa() {
        hilo.suspend();
    }

    //public void continuar() {
    //   hilo.resume();
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        try {
            while (true) {
                while (x < getWidth() - 30) {
                    Thread.sleep(50);
                    x += 10;
                    repaint();
                }
                while (true) {
                    while (x > 10) {
                        Thread.sleep(50);
                        x -= 10;
                        repaint();
                    }
                    while (true) {
                        while (y < getWidth() - 30) {
                            Thread.sleep(50);
                            y += 10;
                            repaint();
                        }
                        while (y > 10) {
                            Thread.sleep(50);
                            y -= 10;
                            repaint();
                        }
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("sucedio un error" + e.getMessage());
        }
    }

    private Image getImage(String caballo1png) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
