/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class canon extends javax.swing.JFrame {

    /**
     * Creates new form PANT
     */
    public canon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();
        encender = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        canal5 = new javax.swing.JButton();
        canal7 = new javax.swing.JButton();
        canal10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        desenfoque = new javax.swing.JButton();
        desenf = new javax.swing.JButton();
        des = new javax.swing.JButton();
        desenfocar = new javax.swing.JButton();
        can = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        Imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        Imagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImagenMouseClicked(evt);
            }
        });

        encender.setText(" ENCENDER ");
        encender.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        encender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encenderMouseClicked(evt);
            }
        });

        apagar.setText("    APAGAR    ");
        apagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        apagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apagarMouseClicked(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jTextField1.setText("     ZOOM     ");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        canal5.setText("25");
        canal5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canal5MouseClicked(evt);
            }
        });

        canal7.setText("50");
        canal7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canal7MouseClicked(evt);
            }
        });

        canal10.setText("100");
        canal10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canal10MouseClicked(evt);
            }
        });

        jButton1.setText("75");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 12)); // NOI18N
        jTextField2.setText("     DESENFOQUE     ");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        desenfoque.setText("25");
        desenfoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desenfoqueMouseClicked(evt);
            }
        });

        desenf.setText("50");
        desenf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desenfMouseClicked(evt);
            }
        });

        des.setText("75");
        des.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desMouseClicked(evt);
            }
        });

        desenfocar.setText("100");
        desenfocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desenfocarMouseClicked(evt);
            }
        });
        desenfocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desenfocarActionPerformed(evt);
            }
        });

        can.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canMouseClicked(evt);
            }
        });

        jButton2.setText("VGA");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HDMI");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(encender)
                                    .addComponent(apagar))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canal5)
                                    .addComponent(jButton1))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canal10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(canal7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(des)
                                    .addComponent(desenfoque))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(desenfocar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desenf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(encender)
                            .addComponent(canal5)
                            .addComponent(canal7)
                            .addComponent(desenfoque)
                            .addComponent(desenf)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(canal10)
                            .addComponent(jButton1)
                            .addComponent(apagar)
                            .addComponent(des)
                            .addComponent(desenfocar)
                            .addComponent(jButton2)))
                    .addComponent(can, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/inicio.png");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

        /*if (jComboBox1.getSelectedItem() == "inicio") {
            Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("inicio.jpg")));
        }
        
        if (jComboBox1.getSelectedItem() == "encen1") {
            Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("encen1.gif")));
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagenMouseClicked

    private void encenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encenderMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/encender.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

        encender.setEnabled(false);
        apagar.setEnabled(true);

        /*if (jComboBox1.getSelectedItem() == "encender") {
            Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("encender.gif")));
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_encenderMouseClicked

    private void apagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apagarMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/apagar.gif");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

        encender.setEnabled(true);
        apagar.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_apagarMouseClicked

    private void canal5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canal5MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/25.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_canal5MouseClicked

    private void canal10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canal10MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/100.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_canal10MouseClicked

    private void canal7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canal7MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/50.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_canal7MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/75.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void desenfoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desenfoqueMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/des25.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);
// TODO add your handling code here:
    }//GEN-LAST:event_desenfoqueMouseClicked

    private void desenfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desenfMouseClicked
        ImageIcon IM = new ImageIcon("src/proyecto/des50.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_desenfMouseClicked

    private void desMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/des25.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);
// TODO add your handling code here:
    }//GEN-LAST:event_desMouseClicked

    private void desenfocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desenfocarMouseClicked
        ImageIcon IM = new ImageIcon("src/proyecto/des100.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);
// TODO add your handling code here:
    }//GEN-LAST:event_desenfocarMouseClicked

    private void desenfocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desenfocarActionPerformed
        ImageIcon IM = new ImageIcon("src/proyecto/75.jpg");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PM);

// TODO add your handling code here:
    }//GEN-LAST:event_desenfocarActionPerformed

    private void canMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canMouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/HDMI.png");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(can.getWidth(), can.getHeight(), Image.SCALE_DEFAULT));
        can.setIcon(PM);

        ImageIcon IM1 = new ImageIcon("src/proyecto/VGA.png");
        Icon PM1 = new ImageIcon(IM.getImage().getScaledInstance(can.getWidth(), can.getHeight(), Image.SCALE_DEFAULT));
        can.setIcon(PM);
// TODO add your handling code here:
    }//GEN-LAST:event_canMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        ImageIcon IM = new ImageIcon("src/proyecto/HDMI.png");
        Icon PM = new ImageIcon(IM.getImage().getScaledInstance(can.getWidth(), can.getHeight(), Image.SCALE_DEFAULT));
        can.setIcon(PM);

        
        ImageIcon IMA = new ImageIcon("src/proyecto/hdmi12.jpg");
        Icon PMA = new ImageIcon(IMA.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PMA);
        /*ImageIcon IMA = new ImageIcon("src/proyecto/25.jpg");
        Icon PMI = new ImageIcon(IMA.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PMI);*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        ImageIcon IM1 = new ImageIcon("src/proyecto/VGA.png");
        Icon PM1 = new ImageIcon(IM1.getImage().getScaledInstance(can.getWidth(), can.getHeight(), Image.SCALE_DEFAULT));
        can.setIcon(PM1);

        
        ImageIcon IMA = new ImageIcon("src/proyecto/vga12.jpg");
        Icon PMA = new ImageIcon(IMA.getImage().getScaledInstance(Imagen.getWidth(), Imagen.getHeight(), Image.SCALE_DEFAULT));
        Imagen.setIcon(PMA);
        // TODO add your 1handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new canon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton apagar;
    private javax.swing.JLabel can;
    private javax.swing.JButton canal10;
    private javax.swing.JButton canal5;
    private javax.swing.JButton canal7;
    private javax.swing.JButton des;
    private javax.swing.JButton desenf;
    private javax.swing.JButton desenfocar;
    private javax.swing.JButton desenfoque;
    private javax.swing.JButton encender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
